"""initial migrations

Revision ID: 4dc74b4ccf15
Revises: d2c41c07e0c6
Create Date: 2022-07-02 09:45:19.248217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc74b4ccf15'
down_revision = 'd2c41c07e0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'seller', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
