"""initial migrations

Revision ID: d2c41c07e0c6
Revises: a4ed898c45aa
Create Date: 2022-06-30 22:16:08.794844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c41c07e0c6'
down_revision = 'a4ed898c45aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneno', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('phoneno')

    # ### end Alembic commands ###
